### ISSUE TITLE
2 asja

### ISSUE THREAD

**Issue by RaunoKa** [PXCode/BillboardX#1]
- [x] Kategooria tekst võiks olla vertikaalne
  (teha see div lihtsalt hästi kitsaks?)
- [x] Ja see horisontaalne skrollimine ei tööta, lisab uue sisu uuele reale
  http://stackoverflow.com/questions/9672176/prevent-floated-divs-from-wrapping-to-new-line
  Seal peaks vist olema lahendus viimasele, hetkel ise ei adu/viitsi.

**Comment by Martsim** [comment]
- [ ] Esialgne suurus div container-le
