### ISSUE TITLE
Regamisel parooliväljade võrdlus (jQuery-ga)

### ISSUE THREAD

**Issue by RaunoKa** [PXCode/BillboardX#26]
Kui keegi jQueryt tahab harjutada siis võiks näiteks  regamislehel parooliväljade erinevuse korral kasutajale märku anda.(välja taust punakaks muuta vms)

**Comment by LeigerVirro** [comment]
Võimalikud variandid:
http://stackoverflow.com/questions/26390759/change-background-color-of-input-field-using-javascript
